/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StokRouteImport } from './routes/stok'
import { Route as SesSistemiRouteImport } from './routes/ses-sistemi'
import { Route as ServisRouteImport } from './routes/servis'
import { Route as RaporlarRouteImport } from './routes/raporlar'
import { Route as OzelOdemelerRouteImport } from './routes/ozel-odemeler'
import { Route as MailOrderRouteImport } from './routes/mail-order'
import { Route as AraclarRouteImport } from './routes/araclar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StokIndexRouteImport } from './routes/stok.index'
import { Route as SesSistemiIndexRouteImport } from './routes/ses-sistemi.index'
import { Route as AraclarIndexRouteImport } from './routes/araclar.index'
import { Route as StokSiparislerRouteImport } from './routes/stok.siparisler'
import { Route as StokSiparisVerRouteImport } from './routes/stok.siparis-ver'
import { Route as SesSistemiTeklifVerRouteImport } from './routes/ses-sistemi.teklif-ver'
import { Route as SesSistemiTeklifGecmisiRouteImport } from './routes/ses-sistemi.teklif-gecmisi'
import { Route as AraclarYeniRouteImport } from './routes/araclar.yeni'

const StokRoute = StokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => rootRouteImport,
} as any)
const SesSistemiRoute = SesSistemiRouteImport.update({
  id: '/ses-sistemi',
  path: '/ses-sistemi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServisRoute = ServisRouteImport.update({
  id: '/servis',
  path: '/servis',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporlarRoute = RaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => rootRouteImport,
} as any)
const OzelOdemelerRoute = OzelOdemelerRouteImport.update({
  id: '/ozel-odemeler',
  path: '/ozel-odemeler',
  getParentRoute: () => rootRouteImport,
} as any)
const MailOrderRoute = MailOrderRouteImport.update({
  id: '/mail-order',
  path: '/mail-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AraclarRoute = AraclarRouteImport.update({
  id: '/araclar',
  path: '/araclar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StokIndexRoute = StokIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StokRoute,
} as any)
const SesSistemiIndexRoute = SesSistemiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SesSistemiRoute,
} as any)
const AraclarIndexRoute = AraclarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AraclarRoute,
} as any)
const StokSiparislerRoute = StokSiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => StokRoute,
} as any)
const StokSiparisVerRoute = StokSiparisVerRouteImport.update({
  id: '/siparis-ver',
  path: '/siparis-ver',
  getParentRoute: () => StokRoute,
} as any)
const SesSistemiTeklifVerRoute = SesSistemiTeklifVerRouteImport.update({
  id: '/teklif-ver',
  path: '/teklif-ver',
  getParentRoute: () => SesSistemiRoute,
} as any)
const SesSistemiTeklifGecmisiRoute = SesSistemiTeklifGecmisiRouteImport.update({
  id: '/teklif-gecmisi',
  path: '/teklif-gecmisi',
  getParentRoute: () => SesSistemiRoute,
} as any)
const AraclarYeniRoute = AraclarYeniRouteImport.update({
  id: '/yeni',
  path: '/yeni',
  getParentRoute: () => AraclarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/araclar': typeof AraclarRouteWithChildren
  '/mail-order': typeof MailOrderRoute
  '/ozel-odemeler': typeof OzelOdemelerRoute
  '/raporlar': typeof RaporlarRoute
  '/servis': typeof ServisRoute
  '/ses-sistemi': typeof SesSistemiRouteWithChildren
  '/stok': typeof StokRouteWithChildren
  '/araclar/yeni': typeof AraclarYeniRoute
  '/ses-sistemi/teklif-gecmisi': typeof SesSistemiTeklifGecmisiRoute
  '/ses-sistemi/teklif-ver': typeof SesSistemiTeklifVerRoute
  '/stok/siparis-ver': typeof StokSiparisVerRoute
  '/stok/siparisler': typeof StokSiparislerRoute
  '/araclar/': typeof AraclarIndexRoute
  '/ses-sistemi/': typeof SesSistemiIndexRoute
  '/stok/': typeof StokIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mail-order': typeof MailOrderRoute
  '/ozel-odemeler': typeof OzelOdemelerRoute
  '/raporlar': typeof RaporlarRoute
  '/servis': typeof ServisRoute
  '/araclar/yeni': typeof AraclarYeniRoute
  '/ses-sistemi/teklif-gecmisi': typeof SesSistemiTeklifGecmisiRoute
  '/ses-sistemi/teklif-ver': typeof SesSistemiTeklifVerRoute
  '/stok/siparis-ver': typeof StokSiparisVerRoute
  '/stok/siparisler': typeof StokSiparislerRoute
  '/araclar': typeof AraclarIndexRoute
  '/ses-sistemi': typeof SesSistemiIndexRoute
  '/stok': typeof StokIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/araclar': typeof AraclarRouteWithChildren
  '/mail-order': typeof MailOrderRoute
  '/ozel-odemeler': typeof OzelOdemelerRoute
  '/raporlar': typeof RaporlarRoute
  '/servis': typeof ServisRoute
  '/ses-sistemi': typeof SesSistemiRouteWithChildren
  '/stok': typeof StokRouteWithChildren
  '/araclar/yeni': typeof AraclarYeniRoute
  '/ses-sistemi/teklif-gecmisi': typeof SesSistemiTeklifGecmisiRoute
  '/ses-sistemi/teklif-ver': typeof SesSistemiTeklifVerRoute
  '/stok/siparis-ver': typeof StokSiparisVerRoute
  '/stok/siparisler': typeof StokSiparislerRoute
  '/araclar/': typeof AraclarIndexRoute
  '/ses-sistemi/': typeof SesSistemiIndexRoute
  '/stok/': typeof StokIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/araclar'
    | '/mail-order'
    | '/ozel-odemeler'
    | '/raporlar'
    | '/servis'
    | '/ses-sistemi'
    | '/stok'
    | '/araclar/yeni'
    | '/ses-sistemi/teklif-gecmisi'
    | '/ses-sistemi/teklif-ver'
    | '/stok/siparis-ver'
    | '/stok/siparisler'
    | '/araclar/'
    | '/ses-sistemi/'
    | '/stok/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mail-order'
    | '/ozel-odemeler'
    | '/raporlar'
    | '/servis'
    | '/araclar/yeni'
    | '/ses-sistemi/teklif-gecmisi'
    | '/ses-sistemi/teklif-ver'
    | '/stok/siparis-ver'
    | '/stok/siparisler'
    | '/araclar'
    | '/ses-sistemi'
    | '/stok'
  id:
    | '__root__'
    | '/'
    | '/araclar'
    | '/mail-order'
    | '/ozel-odemeler'
    | '/raporlar'
    | '/servis'
    | '/ses-sistemi'
    | '/stok'
    | '/araclar/yeni'
    | '/ses-sistemi/teklif-gecmisi'
    | '/ses-sistemi/teklif-ver'
    | '/stok/siparis-ver'
    | '/stok/siparisler'
    | '/araclar/'
    | '/ses-sistemi/'
    | '/stok/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AraclarRoute: typeof AraclarRouteWithChildren
  MailOrderRoute: typeof MailOrderRoute
  OzelOdemelerRoute: typeof OzelOdemelerRoute
  RaporlarRoute: typeof RaporlarRoute
  ServisRoute: typeof ServisRoute
  SesSistemiRoute: typeof SesSistemiRouteWithChildren
  StokRoute: typeof StokRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stok': {
      id: '/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof StokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ses-sistemi': {
      id: '/ses-sistemi'
      path: '/ses-sistemi'
      fullPath: '/ses-sistemi'
      preLoaderRoute: typeof SesSistemiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servis': {
      id: '/servis'
      path: '/servis'
      fullPath: '/servis'
      preLoaderRoute: typeof ServisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raporlar': {
      id: '/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof RaporlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ozel-odemeler': {
      id: '/ozel-odemeler'
      path: '/ozel-odemeler'
      fullPath: '/ozel-odemeler'
      preLoaderRoute: typeof OzelOdemelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-order': {
      id: '/mail-order'
      path: '/mail-order'
      fullPath: '/mail-order'
      preLoaderRoute: typeof MailOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/araclar': {
      id: '/araclar'
      path: '/araclar'
      fullPath: '/araclar'
      preLoaderRoute: typeof AraclarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok/': {
      id: '/stok/'
      path: '/'
      fullPath: '/stok/'
      preLoaderRoute: typeof StokIndexRouteImport
      parentRoute: typeof StokRoute
    }
    '/ses-sistemi/': {
      id: '/ses-sistemi/'
      path: '/'
      fullPath: '/ses-sistemi/'
      preLoaderRoute: typeof SesSistemiIndexRouteImport
      parentRoute: typeof SesSistemiRoute
    }
    '/araclar/': {
      id: '/araclar/'
      path: '/'
      fullPath: '/araclar/'
      preLoaderRoute: typeof AraclarIndexRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/stok/siparisler': {
      id: '/stok/siparisler'
      path: '/siparisler'
      fullPath: '/stok/siparisler'
      preLoaderRoute: typeof StokSiparislerRouteImport
      parentRoute: typeof StokRoute
    }
    '/stok/siparis-ver': {
      id: '/stok/siparis-ver'
      path: '/siparis-ver'
      fullPath: '/stok/siparis-ver'
      preLoaderRoute: typeof StokSiparisVerRouteImport
      parentRoute: typeof StokRoute
    }
    '/ses-sistemi/teklif-ver': {
      id: '/ses-sistemi/teklif-ver'
      path: '/teklif-ver'
      fullPath: '/ses-sistemi/teklif-ver'
      preLoaderRoute: typeof SesSistemiTeklifVerRouteImport
      parentRoute: typeof SesSistemiRoute
    }
    '/ses-sistemi/teklif-gecmisi': {
      id: '/ses-sistemi/teklif-gecmisi'
      path: '/teklif-gecmisi'
      fullPath: '/ses-sistemi/teklif-gecmisi'
      preLoaderRoute: typeof SesSistemiTeklifGecmisiRouteImport
      parentRoute: typeof SesSistemiRoute
    }
    '/araclar/yeni': {
      id: '/araclar/yeni'
      path: '/yeni'
      fullPath: '/araclar/yeni'
      preLoaderRoute: typeof AraclarYeniRouteImport
      parentRoute: typeof AraclarRoute
    }
  }
}

interface AraclarRouteChildren {
  AraclarYeniRoute: typeof AraclarYeniRoute
  AraclarIndexRoute: typeof AraclarIndexRoute
}

const AraclarRouteChildren: AraclarRouteChildren = {
  AraclarYeniRoute: AraclarYeniRoute,
  AraclarIndexRoute: AraclarIndexRoute,
}

const AraclarRouteWithChildren =
  AraclarRoute._addFileChildren(AraclarRouteChildren)

interface SesSistemiRouteChildren {
  SesSistemiTeklifGecmisiRoute: typeof SesSistemiTeklifGecmisiRoute
  SesSistemiTeklifVerRoute: typeof SesSistemiTeklifVerRoute
  SesSistemiIndexRoute: typeof SesSistemiIndexRoute
}

const SesSistemiRouteChildren: SesSistemiRouteChildren = {
  SesSistemiTeklifGecmisiRoute: SesSistemiTeklifGecmisiRoute,
  SesSistemiTeklifVerRoute: SesSistemiTeklifVerRoute,
  SesSistemiIndexRoute: SesSistemiIndexRoute,
}

const SesSistemiRouteWithChildren = SesSistemiRoute._addFileChildren(
  SesSistemiRouteChildren,
)

interface StokRouteChildren {
  StokSiparisVerRoute: typeof StokSiparisVerRoute
  StokSiparislerRoute: typeof StokSiparislerRoute
  StokIndexRoute: typeof StokIndexRoute
}

const StokRouteChildren: StokRouteChildren = {
  StokSiparisVerRoute: StokSiparisVerRoute,
  StokSiparislerRoute: StokSiparislerRoute,
  StokIndexRoute: StokIndexRoute,
}

const StokRouteWithChildren = StokRoute._addFileChildren(StokRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AraclarRoute: AraclarRouteWithChildren,
  MailOrderRoute: MailOrderRoute,
  OzelOdemelerRoute: OzelOdemelerRoute,
  RaporlarRoute: RaporlarRoute,
  ServisRoute: ServisRoute,
  SesSistemiRoute: SesSistemiRouteWithChildren,
  StokRoute: StokRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
